QBShared = QBShared or {}
QBShared.Vehicles = {
	--- Compacts
	["cx75"] = {
		["name"] = "Jaguar",
		["brand"] = "Albany",
		["model"] = "cx75",
		["price"] = 100000,
		["category"] = "super",
		["hash"] = `cx75`,
		["shop"] = "pdm",
	},
	["rmodjeep"] = {
		["name"] = "JeepTrackHawk",
		["brand"] = "Jeep",
		["model"] = "rmodjeep",
		["price"] = 80000,
		["category"] = "suvs",
		["hash"] = `rmodjeep`,
		["shop"] = "pdm",
	},
    ["taycan"] = {
		["name"] = "Taycan",
		["brand"] = "porsche",
		["model"] = "taycan",
		["price"] = 80000,
		["category"] = "sports",
		["hash"] = `taycan`,
		["shop"] = "pdm",
	},
	["subisti08"] = {
		["name"] = "SubaruWRX08",
		["brand"] = "subaru",
		["model"] = "subisti08",
		["price"] = 40000,
		["category"] = "sports",
		["hash"] = `subisti08`,
		["shop"] = "pdm",
	},
	["r8v10"] = {
		["name"] = "AudiR8",
		["brand"] = "subaru",
		["model"] = "r8v10",
		["price"] = 60000,
		["category"] = "sports",
		["hash"] = `r8v10`,
		["shop"] = "pdm",
	},
	["bmeclipse95"] = {
		["name"] = "Eclipse95",
		["brand"] = "mitsubishi",
		["model"] = "bmeclipse95",
		["price"] = 40000,
		["category"] = "sports",
		["hash"] = `bmeclipse95`,
		["shop"] = "pdm",
	},
	["370z"] = {
		["name"] = "Nismo370z",
		["brand"] = "nissan",
		["model"] = "370z",
		["price"] = 800000,
		["category"] = "sports",
		["hash"] = `370z`,
		["shop"] = "pdm",
	},
	["rs6"] = {
		["name"] = "Audirs6",
		["brand"] = "audi",
		["model"] = "rs6",
		["price"] = 900000,
		["category"] = "sports",
		["hash"] = `rs6`,
		["shop"] = "pdm",
	},
	["18performante"] = {
		["name"] = "LamboPerformante",
		["brand"] = "lamborghini",
		["model"] = "18performante",
		["price"] = 3000000,
		["category"] = "super",
		["hash"] = `18performante`,
		["shop"] = "luxury",
	},
	["cam8tun"] = {
		["name"] = "Camry",
		["brand"] = "toyota",
		["model"] = "cam8tun",
		["price"] = 60000,
		["category"] = "sports",
		["hash"] = `cam8tun`,
		["shop"] = "pdm",
	},
	["corolla"] = {
		["name"] = "Corolla",
		["brand"] = "toyota",
		["model"] = "corolla",
		["price"] = 30000,
		["category"] = "sedans",
		["hash"] = `corolla`,
		["shop"] = "pdm",
	},
	["foxsupra"] = {
		["name"] = "Supra",
		["brand"] = "toyota",
		["model"] = "foxsupra",
		["price"] = 60000,
		["category"] = "sports",
		["hash"] = `foxsupra`,
		["shop"] = "pdm",
	},
	["jp12"] = {
		["name"] = "Jeep4Puertas",
		["brand"] = "jeep",
		["model"] = "jp12",
		["price"] = 40000,
		["category"] = "offroad",
		["hash"] = `jp12`,
		["shop"] = "pdm",
	},
	["mlec"] = {
		["name"] = "LancerEvoTech",
		["brand"] = "mitsubishi",
		["model"] = "mlec",
		["price"] = 50000,
		["category"] = "sports",
		["hash"] = `mlec`,
		["shop"] = "pdm",
	},
	["evo10"] = {
		["name"] = "LancerEvo10",
		["brand"] = "mitsubishi",
		["model"] = "evo10",
		["price"] = 80000,
		["category"] = "sports",
		["hash"] = `evo10`,
		["shop"] = "pdm",
	},
	["is350mod"] = {
		["name"] = "Lexus350",
		["brand"] = "lexus",
		["model"] = "is350mod",
		["price"] = 70000,
		["category"] = "sedans",
		["hash"] = `is350mod`,
		["shop"] = "pdm",
	},
	["teslapd"] = {
		["name"] = "TeslaSUV",
		["brand"] = "tesla",
		["model"] = "teslapd",
		["price"] = 60000,
		["category"] = "sports",
		["hash"] = `teslapd`,
		["shop"] = "pdm",
	},
	["sonata20"] = {
		["name"] = "Sonata2020",
		["brand"] = "hyundai",
		["model"] = "sonata20",
		["price"] = 70000,
		["category"] = "sedans",
		["hash"] = `sonata20`,
		["shop"] = "pdm",
	},
	["terzo"] = {
		["name"] = "LamboTerzoMilenio",
		["brand"] = "lamborghini",
		["model"] = "terzo",
		["price"] = 300000,
		["category"] = "super",
		["hash"] = `terzo`,
		["shop"] = "luxury",
	},
	["demonhawk"] = {
		["name"] = "JeepDemonHawk",
		["brand"] = "jeep",
		["model"] = "demonhawk",
		["price"] = 250000,
		["category"] = "super",
		["hash"] = `demonhawk`,
		["shop"] = "luxury",
	},
	["rmodmi8lb"] = {
		["name"] = "BMWConvertiblei8",
		["brand"] = "bmw",
		["model"] = "rmodmi8lb",
		["price"] = 250000,
		["category"] = "super",
		["hash"] = `rmodmi8lb`,
		["shop"] = "luxury",
	},
	["335i"] = {
		["name"] = "BMW335iStreetKingsEdition",
		["brand"] = "bmw",
		["model"] = "335i",
		["price"] = 300000,
		["category"] = "super",
		["hash"] = `335i`,
		["shop"] = "luxury",
	},
	["gle450"] = {
		["name"] = "MercedesGLE450",
		["brand"] = "Mercedes",
		["model"] = "gle450",
		["price"] = 300000,
		["category"] = "sports",
		["hash"] = `gle450`,
		["shop"] = "pdm",
	},
	["fnfcivic"] = {
		["name"] = "civic93",
		["brand"] = "honda",
		["model"] = "fnfcivic",
		["price"] = 40000,
		["category"] = "super",
		["hash"] = `fnfcivic`,
		["shop"] = "pdm",
	},
	["crv"] = {
		["name"] = "hondacrv",
		["brand"] = "honda",
		["model"] = "crv",
		["price"] = 43000,
		["category"] = "suvs",
		["hash"] = `crv`,
		["shop"] = "pdm",
	},
	["tiburon"] = {
		["name"] = "hyundaitiburon",
		["brand"] = "hyundai",
		["model"] = "tiburon",
		["price"] = 30000,
		["category"] = "coupes",
		["hash"] = `tiburon`,
		["shop"] = "pdm",
	},
	["srt8"] = {
		["name"] = "jeepsrt",
		["brand"] = "jeep",
		["model"] = "srt8",
		["price"] = 60000,
		["category"] = "suvs",
		["hash"] = `srt8`,
		["shop"] = "pdm",
	},
	["2020exc"] = {
		["name"] = "ktm",
		["brand"] = "ktm",
		["model"] = "2020exc",
		["price"] = 15000,
		["category"] = "motorcycles",
		["hash"] = `2020exc`,
		["shop"] = "pdm",
	},
	["granlb"] = {
		["name"] = "Maseratiturismo",
		["brand"] = "Maserati",
		["model"] = "granlb",
		["price"] = 40000,
		["category"] = "coupes",
		["hash"] = `granlb`,
		["shop"] = "pdm",
	},
	["ghis2"] = {
		["name"] = "MaseratiGhibli",
		["brand"] = "Maserati",
		["model"] = "ghis2",
		["price"] = 44000,
		["category"] = "sedans",
		["hash"] = `ghis2`,
		["shop"] = "pdm",
	},
	["na6"] = {
		["name"] = "Mazdamiata",
		["brand"] = "Mazda",
		["model"] = "na6",
		["price"] = 25000,
		["category"] = "coupes",
		["hash"] = `na6`,
		["shop"] = "pdm",
	},
	["mz3"] = {
		["name"] = "Mazda3",
		["brand"] = "Mazda",
		["model"] = "mz3",
		["price"] = 30000,
		["category"] = "sedans",
		["hash"] = `mz3`,
		["shop"] = "pdm",
	},
	["rx3"] = {
		["name"] = "Mazdarx3",
		["brand"] = "mazda",
		["model"] = "rx3",
		["price"] = 30000,
		["category"] = "coupes",
		["hash"] = `rx3`,
		["shop"] = "pdm",
	},
	["c63s"] = {
		["name"] = "Mercedes",
		["brand"] = "Mercedes",
		["model"] = "c63s",
		["price"] = 60000,
		["category"] = "coupes",
		["hash"] = `c63s`,
		["shop"] = "pdm",
	},
	["eclipse"] = {
		["name"] = "EclipseGSX",
		["brand"] = "Mitsubishi",
		["model"] = "eclipse",
		["price"] = 30000,
		["category"] = "sports",
		["hash"] = `eclipse`,
		["shop"] = "pdm",
	},
	["eclipsegt06"] = {
		["name"] = "EclipseGT",
		["brand"] = "Mitsubishi",
		["model"] = "eclipsegt06",
		["price"] = 35000,
		["category"] = "sports",
		["hash"] = `eclipsegt06`,
		["shop"] = "pdm",
	},
	["19ramoffroad"] = {
		["name"] = "Ram",
		["brand"] = "Ram",
		["model"] = "19ramoffroad",
		["price"] = 60000,
		["category"] = "offroad",
		["hash"] = `19ramoffroad`,
		["shop"] = "pdm",
	},
	["rculi"] = {
		["name"] = "RollsRoyce",
		["brand"] = "RollsRoyce",
		["model"] = "rculi",
		["price"] = 95000,
		["category"] = "suvs",
		["hash"] = `rculi`,
		["shop"] = "pdm",
	},
	["subwrx"] = {
		["name"] = "SubaruImpreza",
		["brand"] = "Subaru",
		["model"] = "subwrx",
		["price"] = 30000,
		["category"] = "sports",
		["hash"] = `subwrx`,
		["shop"] = "pdm",
	},
	["supra2"] = {
		["name"] = "ToyotaSupra",
		["brand"] = "Toyota",
		["model"] = "supra2",
		["price"] = 50000,
		["category"] = "sports",
		["hash"] = `supra2`,
		["shop"] = "pdm",
	},
	["rubi3d"] = {
		["name"] = "Wrangler",
		["brand"] = "Jeep",
		["model"] = "rubi3d",
		["price"] = 42000,
		["category"] = "offroad",
		["hash"] = `rubi3d`,
		["shop"] = "pdm",
	},
}
